### ISSUE TITLE
node.js crash when data is received...

### ISSUE THREAD

**Issue by Froschie** [derBroBro/private-ma-server#1]
Hope you could help me what I´m doing wrong or is missing.
I´m running the script and nearly every time data is received node.js is crashing with the following message:

_http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (C:\Temp\nodejs\ma-server\node_modules\express\lib\response.js:718:10)
    at ServerResponse.contentType (C:\Temp\nodejs\ma-server\node_modules\express\lib\response.js:551:15)
    at ServerResponse.sendStatus (C:\Temp\nodejs\ma-server\node_modules\express\lib\response.js:339:8)
    at Object.ma.processSensorData (C:\Temp\nodejs\ma-server\ma.js:66:9)
    at C:\Temp\nodejs\ma-server\ma.js:182:14
    at invokeCallback (C:\Temp\nodejs\ma-server\node_modules\raw-body\index.js:262:16)
    at done (C:\Temp\nodejs\ma-server\node_modules\raw-body\index.js:251:7)
    at IncomingMessage.onEnd (C:\Temp\nodejs\ma-server\node_modules\raw-body\index.js:308:7)
    at emitNone (events.js:67:13)

**Comment by derBroBro** [comment]
Hello Froschie,

it looks like an bug where for multi datasets on the first code 200 is send. I this this should only happen on the last set.

Please try to fix it by change the follwing in ma.js (line 64).

FROM

``` javascript
    dstModule.save(dataObj);

    res.sendStatus(200);
  }
```

TO

``` javascript
    dstModule.save(dataObj);
  }
  res.sendStatus(200);
```

It would be great if you tell me is this fixed the issue so I can change in in the project.

Best Malte

**Comment by Froschie** [comment]
Problem solved.
No issue anymore for last few hours.
